// <auto-generated />
using System;
using HungryPizzaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HungryPizzaAPI.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20220703042907_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.ClientePersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5000)");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.EnderecoPersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("VARCHAR(5000)");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.PedidoPersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("NUMERIC(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.PizzaPersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("NUMERIC(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pizzas", (string)null);
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.SaborPersistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)");

                    b.Property<bool>("EmFalta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Preco")
                        .HasColumnType("NUMERIC(4,2)");

                    b.HasKey("Id");

                    b.ToTable("Sabores", (string)null);
                });

            modelBuilder.Entity("PizzaPersistenciaSaborPersistencia", b =>
                {
                    b.Property<int>("PizzasId")
                        .HasColumnType("int");

                    b.Property<int>("SaboresId")
                        .HasColumnType("int");

                    b.HasKey("PizzasId", "SaboresId");

                    b.HasIndex("SaboresId");

                    b.ToTable("PizzasSabores", (string)null);
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.ClientePersistencia", b =>
                {
                    b.HasOne("HungryPizzaAPI.Models.Persistencias.EnderecoPersistencia", "Endereco")
                        .WithOne("Cliente")
                        .HasForeignKey("HungryPizzaAPI.Models.Persistencias.ClientePersistencia", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.PedidoPersistencia", b =>
                {
                    b.HasOne("HungryPizzaAPI.Models.Persistencias.ClientePersistencia", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("HungryPizzaAPI.Models.Persistencias.EnderecoPersistencia", "Endereco")
                        .WithMany("Pedidos")
                        .HasForeignKey("EnderecoId");

                    b.Navigation("Cliente");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.PizzaPersistencia", b =>
                {
                    b.HasOne("HungryPizzaAPI.Models.Persistencias.PedidoPersistencia", "Pedido")
                        .WithMany("Pizzas")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PizzaPersistenciaSaborPersistencia", b =>
                {
                    b.HasOne("HungryPizzaAPI.Models.Persistencias.PizzaPersistencia", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HungryPizzaAPI.Models.Persistencias.SaborPersistencia", null)
                        .WithMany()
                        .HasForeignKey("SaboresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.ClientePersistencia", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.EnderecoPersistencia", b =>
                {
                    b.Navigation("Cliente")
                        .IsRequired();

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("HungryPizzaAPI.Models.Persistencias.PedidoPersistencia", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
